# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    AppBundle\Entity\SchoolYear:
        tags:
          - { name: doctrine.orm.entity_manager, event: postPersistSSchoolYear }
    AppBundle\Entity\Cycle:
        tags:
          - { name: doctrine.orm.entity_manager, event: postPersistSCycle }
    app.studentsHelper:
        class: AppBundle\Services\StudentsHelper
        arguments: ["@doctrine.orm.entity_manager"]
    app.usersHelper:
        class: AppBundle\Services\UsersHelper
        arguments: ["@doctrine.orm.entity_manager", "@fos_user.user_manager"]
    app.companiesHelper:
        class: AppBundle\Services\CompaniesHelper
        arguments: ["@doctrine.orm.entity_manager"]
    app.schoolGroupsHelper:
        class: AppBundle\Services\SchoolGroupsHelper
        arguments: ["@doctrine.orm.entity_manager"]
    app.projectsHelper:
        class: AppBundle\Services\ProjectsHelper
        arguments: ["@doctrine.orm.entity_manager"]
    app.convocatoriesHelper:
        class: AppBundle\Services\ConvocatoriesHelper
        arguments: ["@doctrine.orm.entity_manager"]
    app.distributionprojectHelper:
        class: AppBundle\Services\DistributionsProjectsHelper
        arguments: ["@doctrine.orm.entity_manager"]
    app.modulesHelper:
        class: AppBundle\Services\ModulesHelper
        arguments: ["@doctrine.orm.entity_manager"]
    app.cyclesHelper:
        class: AppBundle\Services\CyclesHelper
        arguments: ["@doctrine.orm.entity_manager"]
    app.coursesHelper:
        class: AppBundle\Services\CoursesHelper
        arguments: ["@doctrine.orm.entity_manager"]
    app.distributionModuleTeacherHelper:
        class: AppBundle\Services\DistributionModuleTeacherHelper
        arguments: ["@doctrine.orm.entity_manager"]
    app.configHelper:
        class: AppBundle\Services\ConfigGeneralHelper
        arguments: ["@doctrine.orm.entity_manager"]
    app.functionsHelper:
        class: AppBundle\Services\FunctionsHelper
        arguments: ["@doctrine.orm.entity_manager"]
    app.courseCycleHelper:
        class: AppBundle\Services\CourseCycleHelper
        arguments: ["@doctrine.orm.entity_manager"]
    app.eventsHelper:
            class: AppBundle\Services\EventsHelper
            arguments: ["@doctrine.orm.entity_manager"]
    app.requestCompany:
            class: AppBundle\Services\RequestCompanyHelper
            arguments: ["@doctrine.orm.entity_manager"]
    app.twig.app_extension:
            class: AppBundle\Twig\AppExtension
            tags:
                - { name: twig.extension }
    app.handler.session_idle:
            class: AppBundle\Handler\SessionIdleHandler
            arguments: ["@session", "@security.token_storage", "@router", %session_max_idle_time%]
            tags:
                - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    AppBundle\DataFixtures\AppFixtures:
           arguments: ["@fos_user.user_manager"]
           tags:
             - { name: doctrine.fixture.orm }